runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(src/.*)
- ^(.git/.*)
- ^(.idea/.*)
- ^(node_modules/.*)

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /assets/(.*)
  static_files: assets/\1
  upload: assets/(.*)

- url: /dist/(.*)
  static_files: dist/\1
  upload: dist/(.*)
